# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Testing

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

concurrency:
  # Cancels jobs running if new commits are pushed
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  physics-driven-ml-tests:

    runs-on: self-hosted
    container: firedrakeproject/firedrake-env:latest
    steps:
    - uses: actions/checkout@v3
    - name: Install torch
      run: |
        pip3 install torch torchvision torchaudio --extra-index-url https://download.pytorch.org/whl/cpu
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Test with pytest
      run: |
        pytest ./tests/