# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Build physics-driven-ml

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

concurrency:
  # Cancels jobs running if new commits are pushed
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  build:

    runs-on: ubuntu-latest
    container:
      image: firedrakeproject/firedrake-vanilla:latest
      options: --user root
    steps:
    # Firedrake's Dockerfile sets USER to firedrake instead of using the default user, so we need to update file permissions for this image to work on GH Actions.
    # See https://help.github.com/en/actions/reference/virtual-environments-for-github-hosted-runners#docker-container-filesystem
    # (copied from https://help.github.com/en/actions/migrating-to-github-actions/migrating-from-circleci-to-github-actions)

    - uses: actions/checkout@v2
    - name: Install torch
      shell: bash
      run: |
        source /home/firedrake/firedrake/bin/activate
        python -m pip3 install torch torchvision torchaudio --extra-index-url https://download.pytorch.org/whl/cpu
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install pytest
        if [ -f requirements.txt ]; then python -m pip install -r requirements.txt; fi
    - name: Test with pytest
      run: |
        python -m pytest ./tests/
